---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - apache2
    - apache2-utils

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apache2/{{ item }}"
    owner: root
    group: root
  with_items:
    - apache2.conf
    - ports.conf
  notify:
    - restart apache
  tags: apache_config

- name: enable modules
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_modules }}"
  notify:
    - restart apache
  tags: apache_config

- name: create macros folder
  file:
    path: /etc/apache2/macros
    state: directory
    owner: root
    group: root

- name: add macros
  template:
    src: "macros/{{ item }}.macro.j2"
    dest: "/etc/apache2/macros/{{ item }}.macro"
    owner: root
    group: root
  with_items:
    - "{{ apache_macros }}"
  notify:
    - restart apache
  tags: apache_config

- name: remove default configuration
  file:
    dest: "/etc/apache2/{{ item }}"
    state: absent
  with_items:
    - sites-available/*
    - sites-enabled/*
  notify:
    - restart apache
  tags: apache_config

- name: add vhosts
  template:
    src: "vhosts/{{ item }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    owner: root
    group: root
  with_items:
    - "{{ apache_vhosts }}"
  notify:
    - restart apache
  tags: apache_config

- name: enable vhosts
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item }}.conf"
    state: link
  with_items:
    - "{{ apache_vhosts }}"
  notify:
    - restart apache
  tags: apache_config

- name: check apache default root
  file:
    path: "{{ apache_www_root }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_user_group }}"
    mode: 0755
  tags: apache_config

- name: add default index
  template:
    src: index.html.j2
    dest: "{{ apache_www_root}}/index.html"
    owner: "{{ apache_user }}"
    group: "{{ apache_user_group }}"
    mode: 0755
  tags: apache_config

- name: service start
  service:
    name:  "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - apache2
